apiVersion: skaffold/v4beta2
kind: Config
metadata:
  name: ticketing
build:
  local: 
    push: false
  artifacts:
  - image: amrnashaat/tickets-auth
    context: auth
    docker:
      dockerfile: Dockerfile
    sync:
      manual:
      - src: 'src/**/*.ts'
        dest: .
manifests:
  rawYaml:
  - infra/auth-depl.yaml
